# roles/flask_app/tasks/main.yml
---
- name: Update apt cache
  apt:
    update_cache: yes

- name: Install required packages
  apt:
    name:
      - python3
      - python3-pip
      - python3-venv
      - git
    state: present

- name: Clone the Flask application repository
  git:
    repo: "{{ flask_app_repo }}"
    dest: "{{ flask_app_dest }}"
    version: "{{ flask_app_branch }}"

- name: Create a virtual environment
  command: python3 -m venv /opt/flask-app/venv
  args:
    creates: /opt/flask-app/venv

- name: Install Flask application dependencies
  pip:
    requirements: /opt/flask-app/requirements.txt
    virtualenv: /opt/flask-app/venv

- name: Copy systemd service file for the Flask application
  copy:
    src: flask-app.service
    dest: /etc/systemd/system/flask-app.service
    owner: root
    group: root
    mode: '0644'

- name: Reload systemd daemon
  systemd:
    daemon_reload: yes

- name: Enable and start the Flask application service
  systemd:
    name: flask-app
    state: started
    enabled: yes

- name: Allow traffic on port 5000 (Flask default port)
  ufw:
    rule: allow
    port: "{{ flask_app_port }}"
    proto: tcp